TTI_LLC/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('import_excel_app/',include('import_excel_app.urls')),
    path('accreditation_app/',include('accredetation_app.urls')),
    path('instructor_app/',include('trainer_app.urls')),
    path('',include('usermanagement_app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

usermanagement_app/urls.py
from django.urls import path
from . import views

app_name = "user_management_app"   


urlpatterns = [
    path("homepage/",views.homepage,name="homepage"),
    path('',views.LoginPage,name='login'),
    path('logout/',views.LogoutPage,name='logout'),
    path('signup/',views.SignupPage,name='signup'),
    # path('render_pdf_view/',views.render_pdf_view,name='render_pdf_view')
    path('rednder_pdf_view/',views.GeneratePdf.as_view(),name='render_pdf_view')

]

usermanagement_app/models.py
from django.db import models

# Create your models here.

usermanagement_app/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
import imp
from django.shortcuts import redirect, render,get_object_or_404
from django.http import HttpResponse
from django.views import View
from django.contrib.auth import logout,login,authenticate
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm #add this
from import_excel_app.models import Excel
from django.contrib import messages #import messages

# Create your views here.
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError


@login_required(login_url='user_management_app:login')
def homepage(request):
	excel = Excel.objects.all()
	return render(request,'index.html',{'excel':excel})


def SignupPage(request):
    if request.method=='POST':
        uname=request.POST.get('username')
        email=request.POST.get('email')
        pass1=request.POST.get('password1')
        pass2=request.POST.get('password2')
        if pass1==pass2:
            if User.objects.filter(email=email):
                error_message = 'The email is already taken. Please chose a diffrent email'
                return redirect('/signup/')
            try:
                # Your code that creates a new user
                user = User.objects.create_user(username=uname, email=email, password=pass1)
            except IntegrityError as e:
                if 'UNIQUE constraint' in str(e) and 'username' in str(e):
                    print(str(e))
                    print("aaaaaaa")
                    # Username already exists, show an error message to the user
                    error_message = 'This username is already taken. Please choose a different username.'
                messages.info(request,error_message)
                return redirect('/signup/')
            if user:
                user.save()
                messages.success(request,f"{uname} has successfully register!!!")
                return redirect('/')
        else:
            messages.info(request,"password and confrom password does'nt match!!")
    return render(request,'signup.html')
def LoginPage(request):
    if request.method=='POST':
        username=request.POST.get('username')
        pass1=request.POST.get('pass')
        user=authenticate(request,username=username,password=pass1)
        if user is not None:
            login(request,user)
            messages.success(request, f"{user} you have loged In successfully!" )
            return redirect('user_management_app:homepage')
        else:
            messages.error(request,f"Username or Password is incorrect!!!")
    return render (request,'signin.html')

@login_required
def LogoutPage(request):
    logout(request)
    return redirect('/')




import os
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from django.contrib.staticfiles import finders


# def link_callback(uri, rel):
#         """
#         Convert HTML URIs to absolute system paths so xhtml2pdf can access those
#         resources
#         """
#         result = finders.find(uri)
#         if result:
#                 if not isinstance(result, (list, tuple)):
#                         result = [result]
#                 result = list(os.path.realpath(path) for path in result)
#                 path=result[0]
#         else:
#                 sUrl = settings.STATIC_URL        # Typically /static/
#                 sRoot = settings.STATIC_ROOT      # Typically /home/userX/project_static/
#                 mUrl = settings.MEDIA_URL         # Typically /media/
#                 mRoot = settings.MEDIA_ROOT       # Typically /home/userX/project_static/media/

#                 if uri.startswith(mUrl):
#                         path = os.path.join(mRoot, uri.replace(mUrl, ""))
#                 elif uri.startswith(sUrl):
#                         path = os.path.join(sRoot, uri.replace(sUrl, ""))
#                 else:
#                         return uri

#         # make sure that file exists
#         if not os.path.isfile(path):
#                 raise Exception(
#                         'media URI must start with %s or %s' % (sUrl, mUrl)
#                 )
#         return path
from django.http import HttpResponse
from django.views.generic import View
import datetime
from .utils import render_to_pdf #created in step 4

class GeneratePdf(View):
    def get(self, request, *args, **kwargs):
        data = {
             'today': datetime.date.today(), 
             'amount': 39.99,
            'customer_name': 'Cooper Mann',
            'order_id': 1233434,
        }
        pdf = render_to_pdf('home/d.html',{
                 'pagesize':'A4',
                 'postingan_list' : data,
            })
        return HttpResponse(pdf, content_type='application/pdf')

# class GeneratePDF(View): 
#     def get(self, request, *args, **kwargs): 
#         template = get_template('invoice.html') 
#         context = { "invoice_id": 123, "customer_name": "John Cooper", "amount": 1399.99, "today": "Today", }
#         html = template.render(context) 
#         pdf = render_to_pdf('invoice.html', context) 
#         if pdf:
#             response = HttpResponse(pdf, content_type='application/pdf') 
#         filename = "Invoice_%s.pdf" %("12341231") 
#         content = "inline; filename='%s'" %(filename) 
#         download = request.GET.get("download") 
#         if download:
#             content = "attachment; filename='%s'" %(filename) 
#             response['Content-Disposition'] = content 
#             return response 
#         return HttpResponse("Not found")

usermanagement_app/templates/hey.html
h<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
    <head>
        <title>Title</title>
        <style type="text/css">
            body {
                font-weight: 200;
                font-size: 14px;
            }
            .header {
                font-size: 20px;
                font-weight: 100;
                text-align: center;
                color: #007cae;
            }
            .title {
                font-size: 22px;
                font-weight: 100;
               /* text-align: right;*/
               padding: 10px 20px 0px 20px;  
            }
            .title {
                color: #007cae;
            }
            .details {
                padding: 10px 20px 0px 20px;
                text-align: left !important;
                /*margin-left: 40%;*/
            }
            .hrItem {
                border: none;
                height: 1px;
                /* Set the hr color */
                color: #333; /* old IE */
                background-color: #fff; /* Modern Browsers */
            }
        </style>
    </head>
    <body>
        <div class='wrapper'>
            <div class='header'>
                <p class='title'>Invoice # </p>
            </div>
        <div>
        <div class='details'>
            Bill to: <br/>
            Amount:  <br/>
            Date: 
            <hr class='hrItem' />
        </div>
    </div>
    </body>
</html>

usermanagement_app/templates/logout.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Home Page</title>
  </head>
  <body>
    <h1>Home Page</h1>
    <a href="{% url 'logout' %}" class="btn btn-primary">Logout</a>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

usermanagement_app/templates/signin.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Design by foolishdeveloper.com -->
  <title>Login Page</title>

  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="/static/css/user/signin.css">



</head>

<body>
  <div class="background">
    <div class="shape"></div>
    <div class="shape"></div>
  </div>
  <form method="post">
    {% csrf_token %}
    <h3>Login Here</h3>
    <label for="username">Username</label>
    <input type="text" placeholder="Enter Username" id="username" name="username" required>

    <label for="password">Password</label>
    <input type="password" placeholder="Password" id="password" name="pass" required>

    <button type="submit">Log In</button>
    <!-- <input type="button" value=""> -->
    <!-- <div class="social">
          <div class="go"><i class="fab fa-google"></i>  Google</div>
          <div class="fb"><i class="fab fa-facebook"></i>  Facebook</div>
        </div> -->
    <a href="{% url 'user_management_app:signup' %}">Create a account</a>

    <!-- script for messages -->
    {% if messages %}
    <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
  </form>

</body>





</html>

usermanagement_app/templates/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Design by foolishdeveloper.com -->
    <title>Signup Page</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/static/css/user/signup.css">

</head>

<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form action="" method="post">
        {% csrf_token %}
        <h3>Signup Here</h3>

        <label for="username">Username</label>
        <input type="text" placeholder="Username" name="username" id="username" required>

        <label for="email">Email</label>
        <input type="email" placeholder="Email or Phone" name="email" id="email" required>

        <label for="password1">Password</label>
        <input type="password" placeholder="Password" id="password1" name="password1" required>


        <label for="password2">Confrom Password</label>
        <input type="password" placeholder="Confrom Password" id="password2" name="password2" required>
        <button type="submit">Signup</button>

        <a href="{% url 'user_management_app:login' %}">i have already account</a>
        {% if messages %}
        <ul class="messages">
          {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </form>
</body>

</html>