TTI_LLC/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('import_excel_app/',include('import_excel_app.urls')),
    path('accreditation_app/',include('accredetation_app.urls')),
    path('instructor_app/',include('trainer_app.urls')),
    path('',include('usermanagement_app.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

usermanagement_app/urls.py
from django.urls import path
from . import views

app_name = "user_management_app"   


urlpatterns = [
    path("homepage/",views.homepage,name="homepage"),
    path('',views.LoginPage,name='login'),
    path('logout/',views.LogoutPage,name='logout'),
    path('signup/',views.SignupPage,name='signup'),
    # path('render_pdf_view/',views.render_pdf_view,name='render_pdf_view')
    path('rednder_pdf_view/',views.GeneratePdf.as_view(),name='render_pdf_view')

]

templates/index.html
<!doctype html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
	<title>TTI_LLC</title>
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="/static/css/bootstrap.min.css">
	<!----css3---->
	<link rel="stylesheet" href="/static/css/custom.css">


	<!--google fonts -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap" rel="stylesheet">


	<!--google material icon-->
	<link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">

	<!-- alertifyjs bootstrap link -->
	<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
	<!-- Default theme -->
	<link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css" />



</head>

<body>



	<div class="wrapper">

		<div class="body-overlay"></div>

		<!-------sidebar--design------------>

		<div id="sidebar">
			<div class="sidebar-header">
				<h3><img src="/static/img/site.jpg" class="img-fluid" /><span>TTI_LLC</span></h3>
			</div>
			<ul class="list-unstyled component m-0">
				<li class="active">
					<a href="#" class="dashboard"><i class="material-icons">dashboard</i>dashboard </a>
				</li>

				<li class="dropdown">
					<a href="#homeSubmenu1" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
						<i class="material-icons">aspect_ratio</i>Upload Excel File
					</a>
					<ul class="collapse list-unstyled menu" id="homeSubmenu1">
						<li><a href="/import_excel_app/import_excel">upload</a></li>
					</ul>
				</li>



				<li class="dropdown">
					<a href="#homeSubmenu5" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
						<i class="material-icons">border_color</i>forms
					</a>
					<ul class="collapse list-unstyled menu" id="homeSubmenu5">
						<li><a href="/accreditation_app/add_accreditaion">add_accreditaion</a></li>
					</ul>
					<ul class="collapse list-unstyled menu" id="homeSubmenu5">
						<li><a href="/instructor_app/add_instructor">add_trainer</a></li>
					</ul>
				</li>
			</ul>
		</div>


		<div id="content">

			<!------top-navbar-start----------->

			<div class="top-navbar">
				<div class="xd-topbar">
					<div class="row">
						<div class="col-2 col-md-1 col-lg-1 order-2 order-md-1 align-self-center">
							<div class="xp-menubar">
								<span class="material-icons text-white">signal_cellular_alt</span>
							</div>
						</div>

						<div class="col-md-5 col-lg-3 order-3 order-md-2">
							<div class="xp-searchbar">
								<form action="{% url 'search_result' %}" method="get" class="inl
									">
									<div class="input-group">
										<input type="search" class="form-control" placeholder="Search" name="search">
										<div class="input-group-append">
											<button class="btn" type="submit" id="button-addon2">Go
											</button>
										</div>
									</div>
								</form>
							</div>
						</div>
						<div class="col-10 col-md-6 col-lg-8 order-1 order-md-3">
							<div class="xp-profilebar text-right">
								<nav class="navbar p-0">
									<ul class="nav navbar-nav flex-row ml-auto">
										<li class="dropdown nav-item">
											<a class="nav-link" href="#" data-toggle="dropdown">
												<img src="/static/img/logo3.avif"
													style="width:50px; border-radius:50%;" />
												<!-- <span class="xp-user-live"></span> -->
											</a>
											<ul class="dropdown-menu small-menu">

												<li><a href="{% url 'user_management_app:logout'%}">
														<span class="material-icons">logout</span>
														Logout
													</a></li>

											</ul>
										</li>


									</ul>
								</nav>
							</div>
						</div>

					</div>

					<div class="xp-breadcrumbbar text-center">
						<h4 class="page-title">Dashboard</h4>
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><a href="#">For Certificate</a></li>
							<li class="breadcrumb-item active" aria-curent="page">Dashboard</li>
						</ol>
					</div>


				</div>
			</div>
			<!------top-navbar-end----------->


			<!------main-content-start----------->

			<div class="main-content">
				<div class="row">
					<div class="col-md-12">
						<div class="table-wrapper">

							<form id="formName" method="get" action="{% url 'checked_delegates' %}">
								<div class="table-title">
									<div class="row">
										<div class="col-sm-6 p-0 flex justify-content-lg-start justify-content-center">
											<h2 class="ml-lg-2">For Certificate</h2>
										</div>
										<div class="col-sm-6 p-0 flex justify-content-lg-end justify-content-center">
											<input type="submit" name="submit" value="DeleteChecked"
												class="btn btn-danger" required />
											<input type="submit" name="submit" value="DownloadChecked"
												class="btn btn-success" required />
										</div>
									</div>
								</div>
								<table class="table table-striped table-hover">
									<thead>
										<tr>
											<th><span class="custom-checkbox">
													<!-- <input type="checkbox" id="selectAll">
												<label for="selectAll"></label></th> -->
											<th>ID No</th>
											<th>Name Of Delegates</th>
											<th>Certifcate NO</th>
											<th>Course</th>
											<th>Company</th>
											<th>Date Of issue</th>
											<th>Date Of Expiry</th>
											<th>Instructor</th>
											<th>Action</th>
										</tr>
									</thead>

									<tbody>
										{% for exc in excel %}
										<tr>
											<th><span class="custom-checkbox">
													<input type="checkbox" id="checkbox1" name="checklist"
														value="{{ exc.id }}">
													<label for="checkbox1"></label></th>
											<th>{{ exc.ID_No }}</th>
											<th>{{ exc.Name_Of_Delegates }}</th>
											<th>{{ exc.Certificate_No }}</th>
											<th>{{ exc.Course }}</th>
											<th>{{ exc.Company }}</th>
											<th>{{ exc.Date_Of_issue }}</th>
											<th>{{ exc.Date_Of_Expiry }}</th>
											<th>{{ exc.Instructor }}</th>

											<th>
												<a href="{% url 'update_specific_delegates' exc.id %}"
													class="btn btn-outline-primary">Update</a>
											</th>
										</tr>

										{% endfor %}
									</tbody>


							</form>
							</table>



						</div>
					</div>
				</div>
			</div>

			<!------main-content-end----------->
		</div>

	</div>

	<!-- show alert message when something happend  -->



	<!-------complete html----------->

	<!-- script for messages -->
	<script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="/static/js/jquery-3.3.1.slim.min.js"></script>
	<script src="/static/js/popper.min.js"></script>
	<script src="/static/js/bootstrap.min.js"></script>
	<script src="/static/js/jquery-3.3.1.min.js"></script>


	<script type="text/javascript">
		$(document).ready(function () {
			$(".xp-menubar").on('click', function () {
				$("#sidebar").toggleClass('active');
				$("#content").toggleClass('active');
			});

			$('.xp-menubar,.body-overlay').on('click', function () {
				$("#sidebar,.body-overlay").toggleClass('show-nav');
			});

		});

	</script>
    {% block content %}
		<script type="">
		{% for  flashmsg in messages %}
		alertify.set('notifier', 'position', 'top-right');
		alertify.success('{{ flashmsg }}');
		{% endfor %}
	
	</script>
	{% endblock %}
</body>

</html>